# Sentence Transformer

- Try BERT instead of SBERT
- Try to find a different SBERT model that's designed for HR
- Replace human resources with hr and try stemming
- Try FastText model
- Look up markov chain monte carlo
- Try alternatives to cosine similarity - BERT has in inbuilt one?

In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from nltk.stem import PorterStemmer

In [20]:
data = pd.read_csv('../data/potential_talents_cleaned.csv')

In [21]:
data.head()

,id,job_title,location,connection,fit,job_title_stem
0,1,2019 c t bauer college of business graduate ...,"Houston, Texas",85,NaN,2019 c t bauer colleg of busi graduat magna cu...
1,2,native english teacher at epik english progra...,Kanada,500+,NaN,nativ english teacher at epik english program ...
2,3,aspiring hr professional,"Raleigh-Durham, North Carolina Area",44,NaN,aspir hr profession
3,4,people development coordinator at ryan,"Denton, Texas",500+,NaN,peopl develop coordin at ryan
4,5,advisory board member at celal bayar university,"İzmir, Türkiye",500+,NaN,advisori board member at celal bayar univers

In [27]:
# choosing sentence transformer model to use
model = SentenceTransformer('all-MiniLM-L6-v2')

# creating embeddings of the words in the job titles
job_embeddings = model.encode(data['job_title'].to_list())

# creating embeddings of the target job title
stemmer = PorterStemmer()
target_title = 'aspiring hr'
target_stem = ' '.join(
    stemmer.stem(word)
    for word in target_title.split()
    )
target_embedding = model.encode([target_stem])

# finding the similarity between each job title and the target
similarities = cosine_similarity(
    target_embedding,
    job_embeddings
).flatten()

# adding the similiarities to the dataframe
data['similarity'] = similarities
data = data.sort_values(by='similarity', ascending=False).reset_index(drop=True)

data

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

,id,job_title,location,connection,fit,job_title_stem,similarity,similarity_stem
0,74,hr professional,Greater Boston Area,16,NaN,hr profession,0.534378,0.520079
1,6,aspiring hr specialist,Greater New York City Area,1,NaN,aspir hr specialist,0.512858,0.875400
2,8,hr senior specialist,San Francisco Bay Area,500+,NaN,hr senior specialist,0.499451,0.499451
3,97,aspiring hr professional,"Kokomo, Indiana Area",71,NaN,aspir hr profession,0.488956,0.841855
4,3,aspiring hr professional,"Raleigh-Durham, North Carolina Area",44,NaN,aspir hr profession,0.488956,0.841855
5,99,seeking hr position,"Las Vegas, Nevada Area",48,NaN,seek hr posit,0.480841,0.519433
6,68,hr specialist at luxottica,Greater New York City Area,500+,NaN,hr specialist at luxottica,0.468996,0.468996
7,88,hr management major,"Milpitas, California",18,NaN,hr manag major,0.450949,0.445643
8,28,seeking hr opportunities,"Chicago, Illinois",390,NaN,seek hr opportun,0.439961,0.561081
9,82,aspiring hr professional an energetic and te...,"Austin, Texas Area",174,NaN,aspir hr profession an energet and team focus ...,0.426797,0.659226
10,10,seeking hr hris and generalist positions,Greater Philadelphia Area,500+,NaN,seek hr hri and generalist posit,0.423304,0.480953
11,83,hr manager at endemol shine north america,"Los Angeles, California",268,NaN,hr manag at endemol shine north america,0.419312,0.378329
12,78,hr generalist at schwan s,Amerika Birleşik Devletleri,500+,NaN,hr generalist at schwan s,0.416899,0.416899
13,75,nortia staffing is seeking hr payroll admin...,"San Jose, California",500+,NaN,nortia staf is seek hr payrol administr profes...,0.391628,0.414315
14,101,hr generalist at loparex,"Raleigh-Durham, North Carolina Area",500+,NaN,hr generalist at loparex,0.387525,0.387525
15,67,hr staffing and recruiting professional,"Jackson, Mississippi Area",500+,NaN,hr staf and recruit profession,0.386295,0.401978
16,89,director hr at ey,Greater Atlanta Area,349,NaN,director hr at ey,0.384883,0.384883
17,71,hr generalist at scottmadden inc,"Raleigh-Durham, North Carolina Area",500+,NaN,hr generalist at scottmadden inc,0.372184,0.372184
18,84,hr professional for the world leader in gis so...,"Highland, California",50,NaN,hr profession for the world leader in gi softwar,0.366571,0.353606
19,13,hr coordinator at intercontinental buckhead at...,"Atlanta, Georgia",500+,NaN,hr coordin at intercontinent buckhead atlanta,0.365192,0.266402
20,73,aspiring hr manager seeking internship in hr,"Houston, Texas Area",7,NaN,aspir hr manag seek internship in hr,0.356830,0.622438
21,79,liberal arts major aspiring hr analyst,"Baton Rouge, Louisiana Area",7,NaN,liber art major aspir hr analyst,0.356303,0.640305
22,66,experienced retail manager and aspiring hr pro...,"Austin, Texas Area",57,NaN,experienc retail manag and aspir hr profession,0.354047,0.549128
23,27,aspiring hr management student seeking an inte...,"Houston, Texas Area",500+,NaN,aspir hr manag student seek an internship,0.333608,0.555161
24,100,aspiring hr manager graduating may 2020 se...,"Cape Girardeau, Missouri",103,NaN,aspir hr manag graduat may 2020 seek an entri ...,0.329690,0.542937
25,76,aspiring hr professional passionate about he...,"New York, New York",212,NaN,aspir hr profession passion about help to crea...,0.327542,0.521967
26,81,senior hr business partner at heil environmental,"Chattanooga, Tennessee Area",455,NaN,senior hr busi partner at heil environment,0.326547,0.394280
27,7,student at humber college and aspiring hr gene...,Kanada,61,NaN,student at humber colleg and aspir hr generalist,0.323599,0.545602
28,69,director of hr north america groupe beneteau,"Greater Grand Rapids, Michigan Area",500+,NaN,director of hr north america group beneteau,0.314656,0.304594
29,70,retired army national guard recruiter office ...,"Virginia Beach, Virginia",82,NaN,retir armi nation guard recruit offic manag se...,0.312584,0.437406
30,12,svp chro marketing communications csr off...,"Houston, Texas Area",500+,NaN,svp chro market commun csr offic engi houston ...,0.311697,0.301442
31,72,business management major and aspiring hr manager,"Monroe, Louisiana Area",5,NaN,busi manag major and aspir hr manag,0.306721,0.582616
32,1,2019 c t bauer college of business graduate ...,"Houston, Texas",85,NaN,2019 c t bauer colleg of busi graduat magna cu...,0.288355,0.487401
33,77,hr \nconflict management \npolicies procedur...,Dallas/Fort Worth Area,409,NaN,hr conflict manag polici procedur talent manag...,0.286561,0.382474
34,11,student at chapman university,"Lake Forest, California",2,NaN,student at chapman univers,0.258354,0.260456
35,104,director of administration at excellence logging,"Katy, Texas",500+,NaN,director of administr at excel log,0.247289,0.211925
36,98,student,"Houston, Texas Area",4,NaN,student,0.233961,0.233961
37,4,people development coordinator at ryan,"Denton, Texas",500+,NaN,peopl develop coordin at ryan,0.226528,0.109084
38,96,student at indiana university kokomo busines...,"Lafayette, Indiana",19,NaN,student at indiana univers kokomo busi manag r...,0.213781,0.203393
39,90,undergraduate research assistant at styczynski...,Greater Atlanta Area,155,NaN,undergradu research assist at styczynski lab,0.212577,0.194983
40,95,student at westfield state university,"Bridgewater, Massachusetts",57,NaN,student at westfield state univers,0.202887,0.171365
41,94,seeking human resources opportunities open t...,Amerika Birleşik Devletleri,415,NaN,seek human resourc opportun open to travel and...,0.197797,0.251220
42,85,rrp brand portfolio executive at jti japan to...,Greater Philadelphia Area,500+,NaN,rrp brand portfolio execut at jti japan tobacc...,0.197353,0.177518
43,80,junior mes engineer information systems,"Myrtle Beach, South Carolina Area",52,NaN,junior me engin inform system,0.195336,0.227236
44,92,seeking employment opportunities within custom...,"Torrance, California",64,NaN,seek employ opportun within custom servic or p...,0.185481,0.242263
45,91,lead official at western illinois university,Greater Chicago Area,39,NaN,lead offici at western illinoi univers,0.184407,0.179500
46,5,advisory board member at celal bayar university,"İzmir, Türkiye",500+,NaN,advisori board member at celal bayar univers,0.151017,0.208883
47,102,business intelligence and analytics at travelers,Greater New York City Area,49,NaN,busi intellig and analyt at travel,0.138607,0.162172
48,86,information systems specialist and programmer ...,"Gaithersburg, Maryland",4,NaN,inform system specialist and programm with a l...,0.134386,0.191216
49,93,admissions representative at community medical...,"Long Beach, California",9,NaN,admiss repres at commun medic center long beach,0.130624,0.224890
50,2,native english teacher at epik english progra...,Kanada,500+,NaN,nativ english teacher at epik english program ...,0.108655,0.153687
51,87,bachelor of science in biology from victoria u...,"Baltimore, Maryland",40,NaN,bachelor of scienc in biolog from victoria uni...,0.102144,0.132613
52,103,always set them up for success,Greater Los Angeles Area,500+,NaN,alway set them up for success,0.070104,0.108525

In [28]:
# choosing sentence transformer model to use
model = SentenceTransformer('all-MiniLM-L6-v2')

# creating embeddings of the words in the job titles
job_embeddings = model.encode(data['job_title_stem'].to_list())

# creating embeddings of the target job title
stemmer = PorterStemmer()
target_title = 'aspiring hr'
target_stem = ' '.join(
    stemmer.stem(word)
    for word in target_title.split()
    )
target_embedding = model.encode([target_stem])

# finding the similarity between each job title and the target
similarities = cosine_similarity(
    target_embedding,
    job_embeddings
).flatten()

# adding the similiarities to the dataframe
data['similarity_stem'] = similarities
data = data.sort_values(by='similarity_stem', ascending=False).reset_index(drop=True)

data

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

,id,job_title,location,connection,fit,job_title_stem,similarity,similarity_stem
0,6,aspiring hr specialist,Greater New York City Area,1,NaN,aspir hr specialist,0.512858,0.875400
1,97,aspiring hr professional,"Kokomo, Indiana Area",71,NaN,aspir hr profession,0.488956,0.841855
2,3,aspiring hr professional,"Raleigh-Durham, North Carolina Area",44,NaN,aspir hr profession,0.488956,0.841855
3,82,aspiring hr professional an energetic and te...,"Austin, Texas Area",174,NaN,aspir hr profession an energet and team focus ...,0.426797,0.659226
4,79,liberal arts major aspiring hr analyst,"Baton Rouge, Louisiana Area",7,NaN,liber art major aspir hr analyst,0.356303,0.640305
5,73,aspiring hr manager seeking internship in hr,"Houston, Texas Area",7,NaN,aspir hr manag seek internship in hr,0.356830,0.622438
6,72,business management major and aspiring hr manager,"Monroe, Louisiana Area",5,NaN,busi manag major and aspir hr manag,0.306721,0.582616
7,28,seeking hr opportunities,"Chicago, Illinois",390,NaN,seek hr opportun,0.439961,0.561081
8,27,aspiring hr management student seeking an inte...,"Houston, Texas Area",500+,NaN,aspir hr manag student seek an internship,0.333608,0.555161
9,66,experienced retail manager and aspiring hr pro...,"Austin, Texas Area",57,NaN,experienc retail manag and aspir hr profession,0.354047,0.549128
10,7,student at humber college and aspiring hr gene...,Kanada,61,NaN,student at humber colleg and aspir hr generalist,0.323599,0.545602
11,100,aspiring hr manager graduating may 2020 se...,"Cape Girardeau, Missouri",103,NaN,aspir hr manag graduat may 2020 seek an entri ...,0.329690,0.542937
12,76,aspiring hr professional passionate about he...,"New York, New York",212,NaN,aspir hr profession passion about help to crea...,0.327542,0.521967
13,74,hr professional,Greater Boston Area,16,NaN,hr profession,0.534378,0.520079
14,99,seeking hr position,"Las Vegas, Nevada Area",48,NaN,seek hr posit,0.480841,0.519433
15,8,hr senior specialist,San Francisco Bay Area,500+,NaN,hr senior specialist,0.499451,0.499451
16,1,2019 c t bauer college of business graduate ...,"Houston, Texas",85,NaN,2019 c t bauer colleg of busi graduat magna cu...,0.288355,0.487401
17,10,seeking hr hris and generalist positions,Greater Philadelphia Area,500+,NaN,seek hr hri and generalist posit,0.423304,0.480953
18,68,hr specialist at luxottica,Greater New York City Area,500+,NaN,hr specialist at luxottica,0.468996,0.468996
19,88,hr management major,"Milpitas, California",18,NaN,hr manag major,0.450949,0.445643
20,70,retired army national guard recruiter office ...,"Virginia Beach, Virginia",82,NaN,retir armi nation guard recruit offic manag se...,0.312584,0.437406
21,78,hr generalist at schwan s,Amerika Birleşik Devletleri,500+,NaN,hr generalist at schwan s,0.416899,0.416899
22,75,nortia staffing is seeking hr payroll admin...,"San Jose, California",500+,NaN,nortia staf is seek hr payrol administr profes...,0.391628,0.414315
23,67,hr staffing and recruiting professional,"Jackson, Mississippi Area",500+,NaN,hr staf and recruit profession,0.386295,0.401978
24,81,senior hr business partner at heil environmental,"Chattanooga, Tennessee Area",455,NaN,senior hr busi partner at heil environment,0.326547,0.394280
25,101,hr generalist at loparex,"Raleigh-Durham, North Carolina Area",500+,NaN,hr generalist at loparex,0.387525,0.387525
26,89,director hr at ey,Greater Atlanta Area,349,NaN,director hr at ey,0.384883,0.384883
27,77,hr \nconflict management \npolicies procedur...,Dallas/Fort Worth Area,409,NaN,hr conflict manag polici procedur talent manag...,0.286561,0.382474
28,83,hr manager at endemol shine north america,"Los Angeles, California",268,NaN,hr manag at endemol shine north america,0.419312,0.378329
29,71,hr generalist at scottmadden inc,"Raleigh-Durham, North Carolina Area",500+,NaN,hr generalist at scottmadden inc,0.372184,0.372184
30,84,hr professional for the world leader in gis so...,"Highland, California",50,NaN,hr profession for the world leader in gi softwar,0.366571,0.353606
31,69,director of hr north america groupe beneteau,"Greater Grand Rapids, Michigan Area",500+,NaN,director of hr north america group beneteau,0.314656,0.304594
32,12,svp chro marketing communications csr off...,"Houston, Texas Area",500+,NaN,svp chro market commun csr offic engi houston ...,0.311697,0.301442
33,13,hr coordinator at intercontinental buckhead at...,"Atlanta, Georgia",500+,NaN,hr coordin at intercontinent buckhead atlanta,0.365192,0.266402
34,11,student at chapman university,"Lake Forest, California",2,NaN,student at chapman univers,0.258354,0.260456
35,94,seeking human resources opportunities open t...,Amerika Birleşik Devletleri,415,NaN,seek human resourc opportun open to travel and...,0.197797,0.251220
36,92,seeking employment opportunities within custom...,"Torrance, California",64,NaN,seek employ opportun within custom servic or p...,0.185481,0.242263
37,98,student,"Houston, Texas Area",4,NaN,student,0.233961,0.233961
38,80,junior mes engineer information systems,"Myrtle Beach, South Carolina Area",52,NaN,junior me engin inform system,0.195336,0.227236
39,93,admissions representative at community medical...,"Long Beach, California",9,NaN,admiss repres at commun medic center long beach,0.130624,0.224890
40,104,director of administration at excellence logging,"Katy, Texas",500+,NaN,director of administr at excel log,0.247289,0.211925
41,5,advisory board member at celal bayar university,"İzmir, Türkiye",500+,NaN,advisori board member at celal bayar univers,0.151017,0.208883
42,96,student at indiana university kokomo busines...,"Lafayette, Indiana",19,NaN,student at indiana univers kokomo busi manag r...,0.213781,0.203393
43,90,undergraduate research assistant at styczynski...,Greater Atlanta Area,155,NaN,undergradu research assist at styczynski lab,0.212577,0.194983
44,86,information systems specialist and programmer ...,"Gaithersburg, Maryland",4,NaN,inform system specialist and programm with a l...,0.134386,0.191216
45,91,lead official at western illinois university,Greater Chicago Area,39,NaN,lead offici at western illinoi univers,0.184407,0.179500
46,85,rrp brand portfolio executive at jti japan to...,Greater Philadelphia Area,500+,NaN,rrp brand portfolio execut at jti japan tobacc...,0.197353,0.177518
47,95,student at westfield state university,"Bridgewater, Massachusetts",57,NaN,student at westfield state univers,0.202887,0.171365
48,102,business intelligence and analytics at travelers,Greater New York City Area,49,NaN,busi intellig and analyt at travel,0.138607,0.162172
49,2,native english teacher at epik english progra...,Kanada,500+,NaN,nativ english teacher at epik english program ...,0.108655,0.153687
50,87,bachelor of science in biology from victoria u...,"Baltimore, Maryland",40,NaN,bachelor of scienc in biolog from victoria uni...,0.102144,0.132613
51,4,people development coordinator at ryan,"Denton, Texas",500+,NaN,peopl develop coordin at ryan,0.226528,0.109084
52,103,always set them up for success,Greater Los Angeles Area,500+,NaN,alway set them up for success,0.070104,0.108525